# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nN3QLEV0pPtsO2-9cd_wyMnRPAoa1vY8
"""

#liste de stockage des articles à acheter:shopping list.
shopping_list=[]
#utilisation du boucle while pour creer un menu d'option.
while True:
  print("1.Ajouter un élément à la liste.")
  print("2.Afficher les éléments de la liste.")
  print("3.Supprimer un élément de la liste.")
  print("4.Quitter la liste.")
  menu_des_options=input("Quelle opération desirez-vous effectuer?")
#fonction if-elif-else  pour determiner la selection à l'utilisateur et effectuer l'action correspondante
  if menu_des_options=="1":
    if len(shopping_list)<3: # fonction pour limiter le nombre des éléments  pouvant etre ajoutés à la liste
#fonction input pour inviter l'utilisateur à faire une selection dans le menu
      choix=input("veuillez entrer l'article à ajouter dans la liste.")
      shopping_list.append(choix)
      print(f"{choix} a été ajouté(e) dans la liste.")
    else:
       print("Votre liste est pleine. Veuillez supprimer certains éléments pour en rajouter d'autres.")
  elif menu_des_options=="2":
    print("Articles de la liste:")
    for choix in shopping_list:
      print(choix)
  elif menu_des_options=="3":
    if len(shopping_list)>1:
       choix=input("Veuillez entrer l'article à supprimer.")
    if choix in shopping_list:
      shopping_list.remove(choix)
      print(f"{choix} a été supprimé(e) de la liste.")
    else:
      print(f"{choix} n'est pas dans la liste.")
  elif menu_des_options=="4":
    print("Merci!")
    break
  else:
    print("Selection invalide. Veuillez entrer une option valide dans le menu d'option.")